version: '2'
services:
    api:
        build:
            context: .
            dockerfile: api.dockerfile
        volumes:
          - ./data:/data
          - ./api:/api:ro
        environment:
          - PUREPAGE_CONFIG=/api/config_product.py
    web:
        build:
            context: .
            dockerfile: web.dockerfile
        volumes:
          - ./web:/web
    nginx:
        image: nginx:stable-alpine
        volumes:
          - ./data:/data
          - ./web/dist:/web:ro
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "80:80"
        depends_on:
          - api
    db:
        image: rethinkdb:latest
        volumes:
          - ./data/rethinkdb:/data
        ports:
          - "8080:8080"
